Repository Meteor-hanaro/Backend, pull requests merged in 2024-06, with the labels that each got.

#32 feature/pb main
  src/main/java/com/hana/app/data/entity/IntegratedPb.java
  src/main/java/com/hana/app/data/entity/IntegratedVip.java
  src/main/java/com/hana/app/data/entity/Users.java
  src/main/java/com/hana/app/repository/ConsultRepository.java
  src/main/java/com/hana/app/repository/IntegratedPbRepository.java
  src/main/java/com/hana/app/repository/IntegratedVipRepository.java
  src/main/java/com/hana/app/repository/UsersRepository.java
  src/main/java/com/hana/app/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/hana/app/service/CustomUserDetailsService.java
  src/main/java/com/hana/app/service/UsersService.java
  src/main/java/com/hana/controller/PbController.java
  src/main/java/com/hana/dto/response/PbDto.java
  src/main/java/com/hana/dto/response/UsersDto.java
Labels: 완료😎, feat🚀

#34 feature/vip-login
  src/main/java/com/hana/controller/UserController.java
  src/main/java/com/hana/controller/VipController.java
Labels: 완료😎, feat🚀

#36 feature/vip main
  src/main/java/com/hana/app/data/entity/Consult.java
  src/main/java/com/hana/app/data/entity/IntegratedVip.java
  src/main/java/com/hana/app/repository/ConsultRepository.java
  src/main/java/com/hana/app/repository/IntegratedPbRepository.java
  src/main/java/com/hana/app/repository/IntegratedVipRepository.java
  src/main/java/com/hana/app/security/SecurityConfig.java
  src/main/java/com/hana/app/service/UsersService.java
  src/main/java/com/hana/controller/VipController.java
  src/main/java/com/hana/dto/response/VipDto.java
Labels: 완료😎, feat🚀

#37 feature/customer-portfolio-management
  src/main/java/com/hana/app/data/entity/portfolio/PortfolioItem.java
  src/main/java/com/hana/app/repository/VipRepository.java
  src/main/java/com/hana/app/repository/security/SecurityPriceRepository.java
  src/main/java/com/hana/app/service/PortfolioItemService.java
  src/main/java/com/hana/app/service/PortfolioService.java
  src/main/java/com/hana/app/service/SecurityPriceService.java
  src/main/java/com/hana/app/service/VipService.java
  src/main/java/com/hana/app/service/fund/FundService.java
  src/main/java/com/hana/app/service/portfolio/PortfolioItemService.java
  src/main/java/com/hana/app/service/portfolio/PortfolioService.java
  src/main/java/com/hana/controller/PortfolioController.java
  src/main/java/com/hana/dto/response/CodeQuantityDto.java
  src/main/java/com/hana/dto/response/PortfolioGraphDto.java
  src/main/java/com/hana/dto/response/PortfolioItemDto.java
  src/main/java/com/hana/dto/response/PortfolioItemResponseDto.java
  src/main/java/com/hana/dto/response/PortfolioResponseDto.java
  src/main/java/com/hana/dto/response/PurchaseCompositionDto.java
  src/test/java/com/hana/fund/SelectFundSecuritiesTests.java
  src/test/java/com/hana/fund/SelectFundTests.java
  src/test/java/com/hana/portfolio/SelectFundGraphDataTests.java
  src/test/java/com/hana/portfolio/SelectPortfolioItemTests.java
  src/test/java/com/hana/portfolio/SelectPortfolioTests.java
Labels: 완료😎, feat🚀

#41 feature/password-check-for-consulting-room
  src/main/java/com/hana/controller/VipController.java
Labels: 완료😎, feat🚀

#42 fix/portfolioitemservice_duplicate_issue_resolve
  src/main/java/com/hana/app/security/SecurityConfig.java
  src/main/java/com/hana/app/service/portfolio/PortfolioItemService.java
  src/main/java/com/hana/app/service/portfolio/PortfolioService.java
  src/main/java/com/hana/dto/response/SuggestionItemCompositionDto.java
Labels: 작업중🤔, fix

#46 feature/users-logout
  src/main/java/com/hana/app/service/UsersService.java
  src/main/java/com/hana/controller/PbController.java
  src/main/java/com/hana/controller/VipController.java
Labels: 완료😎, feat🚀

#47 feature/display vip portfolio suggestion list
  src/main/java/com/hana/config/SwaggerConfig.java
Labels: 완료😎, feat🚀

#48 feature/fundContracts
  src/main/java/com/hana/app/repository/fund/FundContractRepository.java
  src/main/java/com/hana/app/repository/fund/FundRepository.java
  src/main/java/com/hana/app/service/FundContractService.java
  src/main/java/com/hana/controller/ContractController.java
  src/main/java/com/hana/dto/response/FundContractsResponseDto.java
Labels: 완료😎, feat🚀

#50 feature/customer-portfolio-management
  dump.rdb
  src/main/java/com/hana/controller/VipController.java
  src/main/java/com/hana/dto/response/SuggestionItemDto.java
Labels: 완료😎, feat🚀

#51 fix/modify requestMapping
  src/main/java/com/hana/controller/ContractController.java
Labels: 완료😎, fix

#55 feature/users-state-check
  src/main/java/com/hana/app/service/UsersService.java
  src/main/java/com/hana/controller/PbController.java
  src/main/java/com/hana/dto/response/PbDto.java
Labels: 완료😎, feat🚀

#57 feature/webrtcroom_create
  src/main/java/com/hana/app/data/entity/Consult.java
  src/main/java/com/hana/app/data/entity/IntegratedVip.java
  src/main/java/com/hana/app/repository/ConsultRepository.java
  src/main/java/com/hana/app/repository/PbRepository.java
  src/main/java/com/hana/app/repository/UsersRepository.java
  src/main/java/com/hana/app/service/ConsultService.java
  src/main/java/com/hana/app/service/fund/FundContractService.java
  src/main/java/com/hana/app/service/user/PbService.java
  src/main/java/com/hana/app/service/user/UsersService.java
  src/main/java/com/hana/app/service/user/VipService.java
  src/main/java/com/hana/controller/ConsultController.java
  src/main/java/com/hana/controller/ContractController.java
  src/main/java/com/hana/controller/IdentityCheckController.java
  src/main/java/com/hana/controller/PbController.java
  src/main/java/com/hana/controller/VipController.java
  src/main/java/com/hana/dto/request/ConsultRegisterDto.java
  src/main/java/com/hana/dto/request/PbPwdCheckDto.java
  src/main/java/com/hana/dto/response/ConsultSearchDto.java
  src/main/java/com/hana/dto/response/ConsultWebRTCRoomDto.java
  src/main/java/com/hana/dto/response/PbDto.java
  src/main/java/com/hana/dto/response/VipDto.java
Labels: 작업중🤔, feat🚀

#68 fix/error_solve
  src/main/java/com/hana/app/service/user/UsersService.java
Labels: 완료😎, fix

#72 fix/consult-request-pb2vip
  src/main/java/com/hana/app/repository/ConsultRepository.java
  src/main/java/com/hana/app/service/user/UsersService.java
  src/main/java/com/hana/dto/response/VipDto.java
Labels: 완료😎, feat🚀

#75 chore/remove unused dependencies on ContractController
  src/main/java/com/hana/controller/ContractController.java
Labels: chore

#71 feature/system_admin
  src/main/java/com/hana/app/service/MainService.java
  src/main/java/com/hana/controller/MainController.java
Labels: 완료😎, feat🚀

#76 fix/2 PbServices integrated into 1
  src/main/java/com/hana/app/service/ContractService.java
  src/main/java/com/hana/app/service/PbService.java
  src/main/java/com/hana/app/service/user/PbService.java
Labels: fix

#77 fix/apply-jwt-token
  src/main/java/com/hana/app/security/SecurityConfig.java
  src/main/java/com/hana/app/security/jwt/JwtAuthenticationEntryPoint.java
Labels: 완료😎, feat🚀

#81 fix/handle-pb-vip-login
  src/main/java/com/hana/app/service/user/UsersService.java
  src/main/java/com/hana/controller/PbController.java
  src/main/java/com/hana/controller/VipController.java
Labels: 완료😎, fix

#82 feature/suggestion addition
  src/main/java/com/hana/app/data/entity/suggestion/Suggestion.java
  src/main/java/com/hana/app/data/entity/suggestion/SuggestionItem.java
  src/main/java/com/hana/app/repository/suggestion/SuggestionItemRepository.java
  src/main/java/com/hana/app/repository/suggestion/SuggestionRepository.java
  src/main/java/com/hana/app/service/PortfolioItemService.java
  src/main/java/com/hana/app/service/PortfolioService.java
  src/main/java/com/hana/app/service/SuggestionService.java
  src/main/java/com/hana/controller/SuggestionController.java
  src/main/java/com/hana/dto/request/SuggestionApplyRequestDto.java
  src/main/java/com/hana/dto/request/SuggestionApplyRequestItemDto.java
  src/main/java/com/hana/dto/response/SuggestionItemDto.java
  src/main/java/com/hana/dto/response/SuggestionItemObtainDto.java
  src/main/java/com/hana/dto/response/SuggestionObtainDto.java
Labels: 완료😎, feat🚀

#79 feature/system_admin_page_advanced
  src/main/java/com/hana/app/service/ConsultService.java
  src/main/java/com/hana/app/service/SecurityService.java
  src/main/java/com/hana/controller/ConsultController.java
  src/main/java/com/hana/controller/SecurityController.java
  src/main/java/com/hana/dto/response/ConsultAdminDto.java
  src/main/java/com/hana/dto/response/ConsultAdminItemDto.java
  src/main/java/com/hana/dto/response/SecurityDto.java
  src/main/java/com/hana/dto/response/SecurityItemDto.java
  src/test/java/com/hana/portfolio/SelectFundGraphDataTests.java
Labels: 완료😎, feat🚀

#85 feature/handle-consult-ending
  src/main/java/com/hana/app/data/entity/BaseEntity.java
  src/main/java/com/hana/app/data/entity/Consult.java
  src/main/java/com/hana/app/service/ConsultService.java
  src/main/java/com/hana/controller/ConsultController.java
  src/main/java/com/hana/dto/response/ConsultResponseDto.java
Labels: 완료😎, feat🚀

#86 feature/suggestion addition
  src/main/java/com/hana/app/repository/suggestion/SuggestionItemRepository.java
  src/main/java/com/hana/app/repository/suggestion/SuggestionRepository.java
  src/main/java/com/hana/app/service/SuggestionService.java
  src/main/java/com/hana/controller/SuggestionController.java
  src/main/java/com/hana/dto/request/AddFundToSuggestionRequestDto.java
Labels: 완료😎, feat🚀

#67 feature/connect signiture
  src/main/java/com/hana/app/service/fund/FundContractService.java
  src/main/java/com/hana/controller/ContractController.java
  src/main/java/com/hana/controller/SuggestionController.java
Labels: 완료😎, feat🚀
