Repository Meteor-hanaro/Backend, pull requests merged in 2024-05, with the labels that each got.

#4 3 featurejpa config jasypt config
  .gitignore
  build.gradle
  src/main/java/com/hana/app/data/entity/BaseEntity.java
  src/main/java/com/hana/app/data/entity/Consult.java
  src/main/java/com/hana/app/data/entity/Fund.java
  src/main/java/com/hana/app/data/entity/FundContract.java
  src/main/java/com/hana/app/data/entity/FundSecurity.java
  src/main/java/com/hana/app/data/entity/Pb.java
  src/main/java/com/hana/app/data/entity/Portfolio.java
  src/main/java/com/hana/app/data/entity/PortfolioItem.java
  src/main/java/com/hana/app/data/entity/Risktype.java
  src/main/java/com/hana/app/data/entity/Security.java
  src/main/java/com/hana/app/data/entity/SecurityPrice.java
  src/main/java/com/hana/app/data/entity/Suggestion.java
  src/main/java/com/hana/app/data/entity/SuggestionItem.java
  src/main/java/com/hana/app/data/entity/User.java
  src/main/java/com/hana/config/JasyptConfig.java
  src/main/java/com/hana/config/WebMvcConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: feat

#5 Entity 구현
  src/main/java/com/hana/app/data/entity/BaseEntity.java
  src/main/java/com/hana/app/data/entity/Consult.java
  src/main/java/com/hana/app/data/entity/Contract.java
  src/main/java/com/hana/app/data/entity/Fund.java
  src/main/java/com/hana/app/data/entity/FundContract.java
  src/main/java/com/hana/app/data/entity/FundSecurity.java
  src/main/java/com/hana/app/data/entity/Pb.java
  src/main/java/com/hana/app/data/entity/RiskType.java
  src/main/java/com/hana/app/data/entity/Security.java
  src/main/java/com/hana/app/data/entity/SecurityPrice.java
  src/main/java/com/hana/app/data/entity/Suggestion.java
  src/main/java/com/hana/app/data/entity/SuggestionItem.java
  src/main/java/com/hana/app/data/entity/User.java
Labels: feat

#9 Fix: Security id type is string
  src/main/java/com/hana/app/data/entity/Security.java
Labels: fix

#20 feature/S3Setting and fundContract API
  build.gradle
  src/main/java/com/hana/app/data/entity/fund/FundContract.java
  src/main/java/com/hana/app/repository/fund/FundContractRepository.java
  src/main/java/com/hana/app/service/FundContractService.java
  src/main/java/com/hana/controller/ContractController.java
  src/main/java/com/hana/dto/response/FundContractDto.java
  src/main/java/com/hana/exception/NotFoundException.java
  src/main/java/com/hana/external/aws/S3Config.java
  src/main/java/com/hana/external/aws/S3Service.java
  src/main/resources/application-dev.yml
Labels: 완료😎, feat🚀

#21 chore/meteorResponse Refactoring
  src/main/java/com/hana/controller/ContractController.java
  src/main/java/com/hana/response/MeteorResponse.java
Labels: 완료😎

#15 feature/videopage_suggestionlist_logic
  build.gradle
  src/main/java/com/hana/app/data/entity/Pb.java
  src/main/java/com/hana/app/data/entity/User.java
  src/main/java/com/hana/app/data/entity/fund/Fund.java
  src/main/java/com/hana/app/data/entity/portfolio/Portfolio.java
  src/main/java/com/hana/app/data/entity/suggestion/Suggestion.java
  src/main/java/com/hana/app/data/entity/suggestion/SuggestionItem.java
  src/main/java/com/hana/app/repository/portfolio/PortfolioItemRepository.java
  src/main/java/com/hana/app/repository/portfolio/PortfolioRepository.java
  src/main/java/com/hana/app/repository/suggestion/SuggestionItemRepository.java
  src/main/java/com/hana/app/repository/suggestion/SuggestionRepository.java
  src/main/java/com/hana/app/service/PortfolioService.java
  src/main/java/com/hana/app/service/SuggestionService.java
  src/main/java/com/hana/config/SwaggerConfig.java
  src/main/java/com/hana/controller/ContractController.java
  src/main/java/com/hana/controller/FundController.java
  src/main/java/com/hana/controller/PortfolioController.java
  src/main/java/com/hana/controller/SuggestionController.java
  src/main/java/com/hana/dto/response/PortfolioDto.java
  src/main/java/com/hana/dto/response/PortfolioItemDto.java
  src/main/java/com/hana/dto/response/SuggestionDto.java
  src/main/java/com/hana/dto/response/SuggestionItemCompositionDto.java
  src/main/java/com/hana/dto/response/SuggestionItemDto.java
  src/main/resources/application-dev.yml
  src/test/java/com/hana/MeteorBackendApplicationTests.java
Labels: 작업중🤔, feat🚀

#23 22-fix/entity-renewal
  src/main/java/com/hana/app/data/entity/Consult.java
  src/main/java/com/hana/app/data/entity/Contract.java
  src/main/java/com/hana/app/data/entity/Pb.java
  src/main/java/com/hana/app/data/entity/RiskType.java
  src/main/java/com/hana/app/data/entity/Role.java
  src/main/java/com/hana/app/data/entity/User.java
  src/main/java/com/hana/app/data/entity/VIP.java
  src/main/java/com/hana/app/data/entity/portfolio/Portfolio.java
  src/main/java/com/hana/app/service/SuggestionService.java
Labels: 작업중🤔, fix

#28 26 fix/from user to vip
  src/main/java/com/hana/app/data/entity/Pb.java
  src/main/java/com/hana/app/data/entity/Role.java
  src/main/java/com/hana/app/data/entity/VIP.java
  src/main/java/com/hana/app/data/entity/portfolio/Portfolio.java
  src/main/java/com/hana/app/repository/portfolio/PortfolioRepository.java
  src/main/java/com/hana/app/service/PortfolioService.java
  src/main/java/com/hana/app/service/SuggestionService.java
  src/main/java/com/hana/controller/PortfolioController.java
  src/main/java/com/hana/dto/response/PortfolioDto.java
  src/test/java/com/hana/portfolio/SelectPortfolioTests.java
Labels: fix

#29 7 feature/pb login
  build.gradle
  src/main/java/com/hana/PasswordEncoder.java
  src/main/java/com/hana/app/data/entity/Role.java
  src/main/java/com/hana/app/data/entity/Users.java
  src/main/java/com/hana/app/repository/UsersRepository.java
  src/main/java/com/hana/app/security/SecurityConfig.java
  src/main/java/com/hana/app/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/hana/app/security/jwt/JwtTokenProvider.java
  src/main/java/com/hana/app/service/CustomUserDetailsService.java
  src/main/java/com/hana/app/service/UsersService.java
  src/main/java/com/hana/controller/PbController.java
  src/main/java/com/hana/dto/response/UsersDto.java
  src/main/resources/application-dev.yml
Labels: feat🚀
